Update CategorySelectionModal.tsx
Polarts/sentispace pull request #75
Opened 2024-10-07 05:23 UTC by Ziv89

Update CategorySelectionModal UI.

2024-10-09 06:30 UTC, Polarts requested changes
Please adjust the design to look more like this:
![image](https://github.com/user-attachments/assets/1d6c26f7-0935-4bf5-8400-edf7a45f7858)

2024-10-09 06:30 UTC, Polarts commented on src/features/categories/category-selection/CategorySelectionModal.tsx
> +          </Button>
The save button should be removed, since the changes you make are already saved to the activity

2024-10-09 06:30 UTC, Polarts commented on src/features/categories/category-selection/CategorySelectionModal.tsx
> +            iconKey={'MagnifyingGlass'}
Return the `'Binoculars'` icon please

2024-10-09 06:30 UTC, Polarts commented on src/features/categories/category-selection/CategorySelectionModal.tsx
> +      </FullscreenModal.ButtonsPanel> */}
Please restore this code so that we have the "Go Back" button at the bottom.

2024-10-09 11:53 UTC, Ziv89 commented
I did the changes you asked and waiting for a feedback.

2024-10-11 09:09 UTC, Polarts requested changes
There are two issues I found:
1. The X and + buttons are still not aligned vertically
![Screenshot_20241011-120056_Chrome.jpg](https://github.com/user-attachments/assets/d2557576-6a6c-4111-a11a-df6f5fd3732e)
2. When selecting multiple categories they're displayed in a column. Please update it so that multiple can fit in a row.
![Screenshot_20241011-120134_Chrome.jpg](https://github.com/user-attachments/assets/ac75e5c5-046d-4ecf-998a-c69e8a526046)

Also, please make sure you don't push comments that aren't needed. The code speaks for itself and it's readable, you don't need to explain what you did and why in every place you edit.

2024-10-11 09:09 UTC, Polarts commented on src/features/categories/category-selection/CategoryItem.tsx
> +    <div className={classes.sideButton}> {/* Moved to the right */}
Remove the comment here please

2024-10-11 09:09 UTC, Polarts commented on src/features/categories/category-selection/CategorySelect.module.scss
> +  /* Retaining existing styles */
Please clean this file of comments and commented code. They're unnecessary

2024-10-11 09:09 UTC, Polarts commented on src/features/categories/category-selection/CategorySelectionModal.tsx
> +          {/* <Button onClick={handleOnClick} className={classes.saveButton}>
Remove commented code in this file please

2024-10-11 09:09 UTC, Polarts commented on src/features/categories/category-selection/category-badge/CategoryBadge.module.scss
> +  &:hover {
The app is designed for touch, there won't be hover effects. I appreciate the extra but this code can be removed.

2024-10-11 09:09 UTC, Polarts commented on src/features/categories/category-selection/category-badge/CategoryBadge.tsx
> +  onDelete?: () => void; // Add onDelete prop
This comment is unnecessary

2024-10-11 09:09 UTC, Polarts commented on src/features/categories/category-selection/category-badge/CategoryBadge.tsx
> +  onDelete, // Receive onDelete as a prop
This comment is also unnecessary

2024-11-04 16:26 UTC, Polarts requested changes

2024-11-04 16:26 UTC, Polarts commented on src/features/activities/activity-form/ActivityEditForm.module.scss
> +        }
It seems like none of these classes used directly in `ActivityEditForm` but rather refer to the contents of `CategorySelect`. Please move them to `CategorySelect.module.scss`.

2024-11-04 16:26 UTC, Polarts commented on src/features/categories/category-selection/CategorySelect.module.scss
> +  flex: 0 0 calc(25% - 5px);
Please maintain a `camelCase` naming convention for the classes.
Also, please move the classes related to `CategorySelectionModal` into `CategorySelectionModal.module.scss`.

2024-11-04 16:26 UTC, Polarts commented on src/features/categories/category-selection/CategorySelect.module.scss
> +.flexcontainer > div {
Selectors that use the `>` operator for generic tags such as `div` are not healthy. The moment the HTML structure changes, the selector can be wrong and cause bugs.
Please use a class instead.

2024-11-04 16:26 UTC, Polarts commented on src/features/categories/category-selection/CategorySelectionModal.tsx
> +          {/* <Button onClick={handleOnClick} className={classes.saveButton}>
This comment is still relevant.

2024-11-05 09:50 UTC, Ziv89 commented
I am working on the requested changes, will post update version soon.

2024-11-10 12:00 UTC, Polarts approved these changes

2024-11-10 12:01 UTC, merged