Dor hakim
Polarts/sentispace pull request #76
Opened 2024-12-10 13:22 UTC by dorhakim100

Closes #36

2024-12-10 13:32 UTC, Polarts requested changes

2024-12-10 13:32 UTC, Polarts commented on src/features/views/day/day-carousel/DayItem.module.scss
> +  // DorHakim
You don't need to put your name everywhere. Git shows which changes you made.
Please remove all ` // DorHakim` comments.

2024-12-10 13:32 UTC, Polarts commented on src/features/views/day/day-carousel/DayItem.tsx
> +    //     : false
If we were to implement it ourselves, it's not a good implementation.
`toLocaleDateString('he')` creates a string specifically in Hebrew. Why would we want to compare strings, and evben ones with Hebrew characters, when we can compare numbers efficiently?
A better implementation would be comparing `getYear`, `getMonth` and `getDate`.
Either way, the library handles it so you may delete the commented code.

2024-12-10 13:32 UTC, Polarts commented
@nick-vi Run the [preview](https://sentispace-txtn-git-fork-dorhakim100-dorhakim-polarts-projects.vercel.app/) and tell me what you think about the design

2024-12-10 17:08 UTC, nick-vi commented
I like the subtle font change, but the drop shadow doesn’t align with the design language. Please remove the shadow, and we’ll be ready to merge.

2024-12-12 16:28 UTC, Polarts approved these changes

2024-12-12 16:29 UTC, merged